### PR TITLE
Malone12/svcplan 3508/pending perf improvements

### PR DESCRIPTION
**Pull request by jdmaloney**
Improve pending job parsing performance and better handle when partitions have overlapping sub-strings in their name.

### CODE REVIEW

**Comment by jdmaloney** [comment]
@ncsa/asd When possible please review this change for merging.

**Review by bsper2 — APPROVED** [review]
Looks good, just a reminder to rebase those 2 commits into 1

**Comment by jdmaloney** [comment]
@bsper2 Thanks for the review; I believe I've done the rebase right now (tonight) but do you mind giving a final thumbs up before I merge?  I've only squashed commits a couple times and I'm a bit rusty.

**Comment by bsper2** [comment]
Yup looks good thanks!

**Pull request merged**
